workCms/views/codePush.py
import paramiko
import traceback
import logging
from flask import Blueprint, render_template, request, jsonify, session

from workCms.core.auxiliay import session_zsq, dates
from workCms import status_restful_api
from workCms.core.conf import ssh_port
from workCms.modeCls.securityModule import Security

codepush = Blueprint('codepush', __name__)

auditFileDir = "workCms/serviceall/txt/commandAudit.txt"
cmdFileDir = "workCms/serviceall/txt/cmdResult.txt"


def linuxAudit(ipAndHostname: str, code: str):
    s = '，'
    with open(auditFileDir, 'a', encoding='utf8') as f:
        f.write(f"平台执行用户: {session['user_info']}{s} 执行时间: {dates}{s}远程服务器地址: [{ipAndHostname}]{s}执行代码: [{code}]\n")
        f.close()


def sshConnServer(serverIp: str, user: str, passwd: str, port: int, code: str):
    try:
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(hostname=serverIp, port=port, username=user, password=passwd)
        stdin, stdout, stderr = ssh.exec_command(code)
        res = stdout.read()
        err = stderr.read()
        ssh.close()
        if res.decode() == '':
            return err.decode()
        else:
            return res.decode()
    except:
        print(traceback.format_exc())


@codepush.route('/data/audit', endpoint='/data/audit')
@session_zsq
def catAudit():
    f = open(auditFileDir, 'r', encoding='utf8')
    audit_all_text = f.read()
    auditAll = audit_all_text.split('\n')
    # 列表反转
    auditAll.reverse()
    f.close()
    return render_template('audit.html', auditInfo=auditAll)


@codepush.route('/data/res', endpoint='/data/res')
@session_zsq
def catCmdRes():
    f = open(cmdFileDir, 'r', encoding='utf8')
    cmdRes_all_text = f.read()
    f.close()
    return render_template('codepush.html', cmdResInfo=cmdRes_all_text)


@codepush.route('/data/linux', endpoint='/data/linux', methods=['POST', 'GET'])
@session_zsq
def linuxHandle():
    if request.method == 'GET':
        return render_template('codepush.html')
    else:
        serverIp = request.form.get('serverIp')
        user = request.form.get('user')
        passwd = request.form.get('passwd')
        code = request.form.get('code')

        if user == '':
            user = 'root'
        if serverIp == '':
            serverIp = '127.0.0.1'

        obj = Security(code)
        errCode = obj.cmdSecurity()
        if errCode == True:
            logging.error('Execute login user: '+session['user_info']+' '+dates + ' Code has been blocked from executing -> ' + code)
            return jsonify({"code": status_restful_api.HttpCode.serverError, "message": "error,代码执行失败！"})
        else:
            res = sshConnServer(serverIp, user, passwd, ssh_port, code)
            with open(cmdFileDir, 'w', encoding='utf8') as f:
                f.write(res)
                f.close()
        linuxAudit(serverIp, code)
        return jsonify({"code": status_restful_api.HttpCode.success, "message": "代码执行成功！"})


# @codepush.route('/data/linuxcp', endpoint='/data/linuxcp', methods=['POST'])
# @session_zsq
# def linuxCpHandle():
#     src = request.form.get('src')
#     dest = request.form.get('dest')
#     linuxCmd = '\cp -rf' + ' ' + src + ' ' + dest
#     obj_s = Security(src)
#     errCode = obj_s.cmdSpecialStrSecurity()
#     if errCode == True:
#         print('代码已被阻止执行 -> ', src)
#         return jsonify({"code": status_restful_api.HttpCode.serverError, "message": "error,代码执行失败！"})
#     obj_d = Security(dest)
#     errCode = obj_d.cmdSpecialStrSecurity()
#     if errCode == True:
#         print('代码已被阻止执行 -> ', dest)
#         return jsonify({"code": status_restful_api.HttpCode.serverError, "message": "error,代码执行失败！"})
#     try:
#         res = os.system(linuxCmd)
#         if res != 1:
#             return jsonify({"code": status_restful_api.HttpCode.success, "message": "拷贝成功!"})
#         else:
#             return jsonify({"code": status_restful_api.HttpCode.serverError, "message": "error,执行拷贝失败!!!"})
#     except:
#         return jsonify({"code": status_restful_api.HttpCode.serverError, "message": "error,执行拷贝失败!!!"})

workCms/views/event.py
from flask import render_template, request, Blueprint

from workCms.databases.mysql_db import cursor, conn
from workCms.core.auxiliay import session_zsq

eventJL = Blueprint('event', __name__)


@eventJL.route('/event_w', endpoint='event_w', methods=['GET'])
@session_zsq
def event_w():
    return render_template('event_w.html')


@eventJL.route('/event_w_database', endpoint='event_w_database', methods=['POST'])
@session_zsq
def event_w_database():
    event_date = request.form.get('date')
    event_info = request.form.get('info')
    event_name = request.form.get('eventName')

    cursor.execute(
        "INSERT INTO event (event_date, event_info, event_name) VALUES (%(event_date)s, %(event_info)s, %(event_name)s)",
        {
            "event_date": event_date,
            "event_info": event_info,
            "event_name": event_name
        })
    conn.commit()
    return ''


@eventJL.route('/event_zs', endpoint='event_zs')
@session_zsq
# @execute_time_decorator
def event_zs():
    cursor.execute("select * from event order by event_id desc limit 200")
    results = cursor.fetchall()
    return render_template('event_zs.html', data=results)

@eventJL.route('/event_sx', endpoint='event_sx', methods=['POST'])
@session_zsq
def event_sx():
        start_num = request.form.get('start_num')
        stop_num = request.form.get('stop_num')
        if start_num == '' or stop_num == '':
            return render_template('event_zs.html')
        sql = """
            select * from event limit {s},{e}
        """.format(s=start_num, e=stop_num)
        cursor.execute(sql)
        results = cursor.fetchall()
        return render_template('event_zs.html', data=results)


@eventJL.route('/event_search', endpoint='event_search', methods=['GET', 'POST'])
@session_zsq
def event_search():
    search = request.form['search']
    if search == '':
        return render_template('event_zs.html')
    sql = """
                select * from event where event_info like '%{name}%'  order by event_id desc
        """.format(name=search)
    cursor.execute(sql)
    results = cursor.fetchall()
    return render_template('event_zs.html', data=results)

workCms/views/file.py
from flask import render_template, request, Blueprint, jsonify, send_file
import os, traceback
from pathlib import Path

from workCms.core.auxiliay import session_zsq, dates
from workCms.core.conf import data_save

file = Blueprint('file', __name__)


@file.route('/push', endpoint='push')
@session_zsq
def push():
    backupDir = []

    systemSave_dir = data_save
    v = os.path.exists(systemSave_dir)
    if v == True:
        backupData = []
        files_dir = os.listdir(systemSave_dir)
        for i in files_dir:
            my_file = Path(systemSave_dir + "/" + i)
            if my_file.is_dir():
                backupData.append(i)
    else:
        return jsonify({"ERROR": {
            "status": "error",
            "errorInfo": "主目录不存在，请手动创建目录!",
            "tips": "配置frag.yaml中PushData_save_dir字段."
        }})

    files_dir = os.listdir(data_save)
    for file in files_dir:
        backupDir.append(file)
    return render_template('push.html', backupData=backupData, backupDir=backupDir)


@file.route('/push_w', endpoint='push_w', methods=['POST'])
@session_zsq
def push_w():
    backupData = []
    backupDir = []
    try:
        saveDir = request.form['num']
        file_data = request.files.getlist('file')
        for file in file_data:
            file.save(os.path.join(data_save + saveDir, file.filename))

        files_dir = os.listdir(data_save)
        for i in files_dir:
            my_dir = Path(data_save + i)
            if my_dir.is_dir():
                backupDir.append(i)

        datadir = os.listdir(data_save + saveDir)
        for x in datadir:
            backupData.append(x)

        return render_template('push.html', status="文件上传成功", backupDir=backupDir, backupData=backupData)
    except:
        print("push_w" + " " + dates + '  上传数据有错误！！！\n' + traceback.format_exc())

        files_dir = os.listdir(data_save)
        for file in files_dir:
            backupDir.append(file)
        return render_template('push.html', status="文件上传失败", backupDir=backupDir, backupData=backupData)


@file.route('/download', endpoint='/download')
@session_zsq
def download():
    # 浏览器下载链接: http://ip:port/download?file_name=1.sh&file_dir=test
    # linux下载链接: curl -# -o 1.txt http://ip:port/download?file_name=1.sh&file_dir=test
    file_name = request.args.get('file_name')
    file_dir = request.args.get('file_dir')
    path = data_save + file_dir + '/' + '%s' % file_name
    return send_file(path, as_attachment=True)

workCms/views/secure.py
from flask import Blueprint, render_template, request, jsonify
import traceback

from workCms.core.auxiliay import session_zsq, execute_time_decorator
from workCms.core.sysSecure import count_frag_access_ip, count_sys_ip
from workCms.modeCls.iptablesModule import Iptables

secure = Blueprint('secure', __name__)


def frag() -> (list, dict):
    frag_ip_status = dict()
    frag_rel = count_frag_access_ip()
    for i in frag_rel:
        s = Iptables(i)
        b = s.show_cl_status()
        frag_ip_status[i] = b
    return frag_rel, frag_ip_status


def sys() -> (list, dict):
    sys_ip_status = dict()
    sys_rel = count_sys_ip()
    for i in sys_rel:
        s = Iptables(i)
        b = s.show_cl_status()
        sys_ip_status[i] = b
    return sys_rel, sys_ip_status


@secure.route('/secure/index/', endpoint='/secure/index')
@session_zsq
def secure_index():
    frag_rel, frag_ip_status = frag()
    sys_rel, sys_ip_status = sys()
    return render_template("secure.html", frag_ip_dict=frag_rel,
                           frag_ip_status=frag_ip_status,
                           sys_ip_dict=sys_rel,
                           sys_ip_status=sys_ip_status)


@secure.route('/secure/cl/drop/drop', endpoint='/secure/cl/drop/drop', methods=['POST'])
@session_zsq
def secure_cl_drop():
    use_status = request.form.get("drop_status")
    lists = use_status.split('\t')
    ip = lists[1]
    i = Iptables(ip)
    b = i.dorp()
    if b:
        return jsonify({"code": 200, "message": "禁止成功."})
    else:
        return jsonify({"code": 500, "message": "禁止失败."})


@secure.route('/secure/cl/drop/del', endpoint='/secure/cl/drop/del', methods=['POST'])
@session_zsq
def secure_cl_del_drop():
    del_status = request.form.get("delDrop_status")
    del_list = del_status.split('\t')
    ip = del_list[1]
    i = Iptables(ip)
    b = i.del_drop()
    if b:
        return jsonify({"code": 200, "message": "解封成功."})
    else:
        return jsonify({"code": 500, "message": "解封失败."})


@secure.route('/secure/ip/index', endpoint='/secure/ip/index')
@session_zsq
def ip_index():
    return render_template('ipInfo.html')


@secure.route('/secure/ip', endpoint='/secure/ip', methods=['POST'])
# @execute_time_decorator
# 访问格式 http://127.0.0.1:14000/secure/ip?addr=114.114.114.114
def show_ip_info():
    # ip = request.args.get("addr")
    ip = request.form.get("addr")
    s = Iptables(ip)
    try:
        c, f = s.get_country_by_ip()
        return render_template('ipInfo.html',
                               ip=ip,
                               country=c,
                               info=f
                               )
    except:
        print(traceback.format_exc())
        return render_template('ipInfo.html', error="ip addr query fail, network timeout.")

workCms/views/serverCheck.py
from flask import Blueprint
from flask import render_template, request

from workCms.core.auxiliay import session_zsq
from workCms.databases.mysql_db import cursor, conn
from workCms import status_restful_api
from workCms.modeCls.alertModule import Alert

server_check = Blueprint('server_check', __name__)


@server_check.route("/server", endpoint="server")
@session_zsq
def serverCheck():
    return render_template('serverCheck.html')


@server_check.route("/server_w_database", endpoint='server_w_database', methods=['POST'])
@session_zsq
def server_w():
    datatime = request.form.get('datetime')
    serverName = request.form.get('serverName')
    dataBackup = request.form.get('dataBackup')
    serverStatus = request.form.get('serverStatus')
    policeNum = request.form.get('policeNum')
    policeInfo = request.form.get('policeInfo')
    checkName = request.form.get('checkName')
    cursor.execute(
        "INSERT INTO server (server_date, server_name, server_dataBackup, server_status, server_policeNum, server_info, server_userName) VALUES"
        "(%(server_date)s, %(server_name)s, %(server_dataBackup)s, %(server_status)s, %(server_policeNum)s, %(server_info)s,%(checkName)s)",
        {
            "server_date": datatime,
            "server_name": serverName,
            "server_dataBackup": dataBackup,
            "server_status": serverStatus,
            "server_policeNum": policeNum,
            "server_info": policeInfo,
            "checkName": checkName
        })
    conn.commit()
    return status_restful_api.success(message="数据提交成功！")


@server_check.route("/server_zs", endpoint="server_zs")
@session_zsq
def server_zs():
    cursor.execute("select * from server order by server_id desc limit 200")
    server_results = cursor.fetchall()
    return render_template("serverCheck_zs.html", rel=server_results)

@server_check.route('/server_sx', endpoint='server_sx', methods=['POST'])
@session_zsq
def server_sx():
        start_num = request.form.get('start_num')
        stop_num = request.form.get('stop_num')
        if start_num == '' or stop_num == '':
            return render_template('serverCheck_zs.html')
        sql = """
            select * from server limit {s},{e}
        """.format(s=start_num, e=stop_num)
        cursor.execute(sql)
        results = cursor.fetchall()
        return render_template('serverCheck_zs.html', rel=results)


@server_check.route('/server_search', endpoint='server_search', methods=['GET', 'POST'])
@session_zsq
def deploy_search():
    search = request.form['search']
    if search == '':
        return render_template('serverCheck_zs.html')
    sql = """
        select * from server where server_info like '%{name}%'  order by server_id desc
    """.format(name=search)
    cursor.execute(sql)
    results = cursor.fetchall()
    return render_template('serverCheck_zs.html', rel=results)


@server_check.route('/server/alert', endpoint='/server/alert')
@session_zsq
def alert():
    alerts = Alert()
    all_res = alerts.allAlertResult()
    today_date = alerts.todayDateResult()
    day_res = alerts.alldayAlertResult(today_date)
    alert_str, alert_num = alerts.alertScreen()
    return render_template('alertGather.html', all=all_res, day=day_res, str=alert_str, num=alert_num)

workCms/views/shut.py
from flask import jsonify, render_template, request, Blueprint
from collections import Counter
from workCms.databases.mysql_db import cursor, conn
from workCms.core.auxiliay import session_zsq

hefuJL = Blueprint('hefu', __name__)


@hefuJL.route('/hefu_data_handle', endpoint='hefu_data_handle', methods=['GET', 'POST'])
@session_zsq
def hefu_data_handle():
    conn.ping(reconnect=True)
    print("Connected!")
    cursor.execute("select * from hefu order by hefu_id desc")
    hefu_results = cursor.fetchall()

    date = []
    for i in hefu_results:
        for k, v in i.items():
            if k == "hefu_date":
                date.append(v)
    hefuAndDate = dict(Counter(date))
    return jsonify(
        dates=[k for k, _ in hefuAndDate.items()],
        hefu_num=[v for _, v in hefuAndDate.items()]
    )


@hefuJL.route('/hefu_w', endpoint='hefu_w', methods=['GET', 'POST'])
@session_zsq
def hefu_w():
    return render_template('hefu_w.html')


@hefuJL.route('/hefu_w_database', endpoint='hefu_w_database', methods=['GET', 'POST'])
@session_zsq
def hefu_w_database():
    hefu_date = request.form.get('date')
    hefu_time = request.form.get('time')
    hefu_info = request.form.get('info')
    hefuName = request.form.get('hefuName')

    cursor.execute(
        "INSERT INTO hefu (hefu_date, hefu_time, hefu_info, hefu_name)VALUES (%(hefu_date)s, %(hefu_time)s, %(hefu_info)s, %(hefu_name)s)",
        {
            "hefu_date": hefu_date,
            "hefu_time": hefu_time,
            "hefu_info": hefu_info,
            "hefu_name": hefuName
        })
    conn.commit()
    return 'ok'


@hefuJL.route('/hefu_zs', endpoint='hefu_zs', methods=['GET', 'POST'])
@session_zsq
# @execute_time_decorator
def hefu_zs():
    conn.ping(reconnect=True)
    cursor.execute("select * from hefu order by hefu_id desc limit 200")
    results = cursor.fetchall()
    return render_template('hefu_zs.html', data=results)

@hefuJL.route('/hefu_sx', endpoint='hefu_sx', methods=['POST'])
@session_zsq
def hefu_sx():
        start_num = request.form.get('start_num')
        stop_num = request.form.get('stop_num')
        if start_num == '' or stop_num == '':
            return render_template('hefu_zs.html')
        sql = """
            select * from hefu limit {s},{e}
        """.format(s=start_num, e=stop_num)
        cursor.execute(sql)
        results = cursor.fetchall()
        return render_template('hefu_zs.html', data=results)


@hefuJL.route('/hefu_search', endpoint='hefu_search', methods=['GET', 'POST'])
@session_zsq
def hefu_search():
    search = request.form['search']
    if search == '':
        return render_template('hefu_zs.html')
    sql = """
            select * from hefu where hefu_info like '%{name}%'  order by hefu_id desc
        """.format(name=search)
    cursor.execute(sql)
    results = cursor.fetchall()
    return render_template('hefu_zs.html', data=results)

workCms/templates/audit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>audit</title>
    <link rel="stylesheet" href={{ url_for('static', filename='css/tools/bootstrap.min.css') }}>
</head>
<body>
    <h4 style="color: #6d61ea">审计日志</h4>
    <hr>
    <div>
        <table class="table table-bordered table-hove">
            <tbody>
                {% for i in auditInfo %}
                    <tr style="background-color: #6d61ea; color: #eeeeee">
                        {% if i != '' %}
                            <td>{{ i }}</td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

workCms/templates/cmdRes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>cmdres</title>
    <link rel="stylesheet" href={{ url_for('static', filename='css/tools/bootstrap.min.css') }}>
</head>
<body>
    <div>
        <li>
            <span>原文格式</span>
        </li>
        <hr>
        <div>
            <pre class="text-white bg-dark">{{ cmdResInfo }}</pre>
        </div>
    </div>
</body>
</html>

workCms/templates/documentscat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>documentscat</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='js/highlight/styles/github-dark-dimmed.min.css') }}">
    <script src="{{ url_for('static', filename='js/highlight/highlight.min.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/documents.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/tools/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/all.css') }}">
    <script>hljs.highlightAll();</script>
</head>

<body>
    <h4 style="color: #6d61ea">文章详情</h4>
    <span><b>标题:</b> {{ filename }}</span>
    <span><b>发布时间:</b> {{ filedate }}</span>
    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <span><b>看累了就听首歌^_^</b></span>
        <audio class="musics" controls="controls" loop="true" src="/static/music/{{ music }}"></audio>
    <br><br>
    <hr>

    {% for i in fileRel %}
        {% for _, v in i.items() %}
           {# safe转义html#}
            <div class="post-content">
                {{ v|safe }}
            </div>
        {% endfor %}
    {% endfor %}

</body>
</html>

workCms/templates/event_zs.html
<!DOCTYPE html>
<body lang="en">

<head>
    <meta charset="UTF-8">
    <title>事件记录展示</title>
    <link rel="stylesheet" href={{ url_for('static', filename='css/tools/bootstrap.min.css') }}>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/all.css') }}">
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.6.1.min.js') }}"></script>
</head>

<body>
    <div class="container">
        <form class="parent" method="post" action="{{ url_for('event.event_search') }}">
            <input name="search" type="text" placeholder="输入关键字">
            <input type="submit" value="搜索记录">
        </form>
    </div>

    <div style="float: left; display: flex; align-items: center;">
        <input type="text" id="data" style="height: 36px;" placeholder="输入要删除的ID">
        <button class="btn btn-danger" id="delete_table" style="margin: 2px;">删除</button>
    </div>

    <div>
        <form action="{{ url_for('event.event_sx') }}" method="post" style="float: left; display: flex; align-items: center;margin-left: 20px">
            <input type="text" id="start_num"  name="start_num" style="height: 36px; width: 80px" placeholder="100">
            <input type="text" id="stop_num" name="stop_num" style="height: 36px; width: 80px; margin: 2px;" placeholder="200">
            <input class="btn btn-primary" type="submit" value="筛选查看" data-toggle="tooltip" data-placement="left" title="第一个输入框是从哪行开始，第二个输入框是基于前面的输入框数字往后的多少行，输入的数字。">
        </form>
    </div>

    <div>
        <form method="post" name="chack_deploy" style="margin-top: 70px">
            <table class="table table-bordered table-hove">
                 <thead>
                    <tr>
                        <th>ID</th>
                        <th>事件日期</th>
                        <th>事件详情</th>
                        <th>执行人</th>
                    </tr>
                </thead>
                <tbody id="tablesData">
                    {% for i in data %}
                    <tr>
                        {% for _,v in i.items() %}
                        <td>{{v}}</td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </form>
    </div>

    <div id="barcon" class="barcon" >
        <div id="barcon2" class="barcon2">
            <ul style="display: flex; align-items: center">
                <li><a id="prePage" style="border-radius: 3px; text-decoration: none;">上一页</a></li>
                <li id="barcon1"></li>
                <li><a id="nextPage" style="border-radius: 3px; text-decoration: none;">下一页</a></li>
                <li style="margin-left: 3px"><input type="text" id="num" size="2" oninput="value=value.replace(/[^\d]/g,'')"></li>
                <li><a id="jumpPage" style="border-radius: 3px; text-decoration: none;margin-left: 3px;color: #eeeeee" onclick="jumpPage()">跳转</a></li>
            </ul>
        </div>
    </div>

    <script src="{{ url_for('static', filename='js/event.js') }}"></script>

    <script type="text/javascript">
        $(function(){
            goPage(1,100);
        })
        var pageSize=1;
        var currentPage_=1;
        var totalPage;
        function goPage(pno,psize){
            var itable = document.getElementById("tablesData");
            var num = itable.rows.length;

            pageSize = psize;
            if(num/pageSize > parseInt(num/pageSize)){
                totalPage=parseInt(num/pageSize)+1;
            }else{
                totalPage=parseInt(num/pageSize);
            }
            var currentPage = pno;
            currentPage_=currentPage;
            var startRow = (currentPage - 1) * pageSize+1;
            var endRow = currentPage * pageSize;
            endRow = (endRow > num)? num : endRow;

            $("#tablesData tr").hide();
            for(var i=startRow-1;i<endRow;i++) {
                $("#tablesData tr").eq(i).show();
            }

            var tempStr = currentPage+"/"+totalPage;
            document.getElementById("barcon1").innerHTML = tempStr;

            if(currentPage>1){
                $("#firstPage").on("click",function(){
                    goPage(1,psize);
                }).removeClass("ban");
                $("#prePage").on("click",function(){
                    goPage(currentPage-1,psize);
                }).removeClass("ban");
            }else{
                $("#firstPage").off("click").addClass("ban");
                $("#prePage").off("click").addClass("ban");
            }

            if(currentPage<totalPage){
                $("#nextPage").on("click",function(){
                    goPage(currentPage+1,psize);
                }).removeClass("ban")
                $("#lastPage").on("click",function(){
                    goPage(totalPage,psize);
                }).removeClass("ban")
            }else{
                $("#nextPage").off("click").addClass("ban");
                $("#lastPage").off("click").addClass("ban");
            }
        }

        function jumpPage() {
            var num=parseInt($("#num").val());
            if(num != currentPage_ && !isNaN(num) && num <= totalPage && num > 0) {
                goPage(num,pageSize);
            }
        }
    </script>

</body>
</html>

workCms/templates/hefu_w.html
<!DOCTYPE html>
<body lang="en">
<head>
    <meta charset="UTF-8">
    <title>合服详情记录</title>
    <link rel="stylesheet" href={{ url_for('static', filename='css/tools/bootstrap.min.css') }}>
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.6.1.min.js') }}"></script>
</head>
 
<body>
    <br \>
    <form>
        <div class="form-group">

          <label>合服日期</label>
          <input id="date" name="hefu_date" type="text" class="form-control"  placeholder="2022/8/1">

          <label>合服时间</label>
          <input id="time" name="hefu_time" type="text" class="form-control"  placeholder="9:00-11:00">

          <label>合服详情</label>
          <textarea id="info" name="hefu_info" type="text" class="form-control"  rows="3"></textarea>
            <label>执行人</label>
          <input id="hefuName" name="hefu_name" type="text" class="form-control">

          <br><br>

          <button id="tj" class="btn btn-primary">提交记录</button>
          <input class="btn btn-warning" type="reset" value="重置">
          <a href="{{ url_for('hefu.hefu_zs') }}">
            <button type="button" class="btn btn-info">查看合服记录</button>
          </a>
        </div>
      </form>

      <script src="{{ url_for('static', filename='js/shut.js') }}"></script>
</body>
</html>

workCms/templates/push.html
<!DOCTYPE html>
<html>
<head>
    <title>文件上传</title>
    <link rel="stylesheet" href={{ url_for('static', filename='css/tools/bootstrap.min.css') }}>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/all.css') }}">
    <script src="{{ url_for('static', filename='js/jquery-3.6.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/all.js') }}"></script>
</head>

<body>

    <form class="#" method="post" action="{{ url_for('file.push_w') }}" enctype="multipart/form-data">
            {% for filedata in listdir %}
                <option>{{filedata}}</option>
            {% endfor %}
    </form>

    <form action="{{ url_for('file.push_w') }}" method="POST"  enctype="multipart/form-data">
        <span><b>目录选择</b></span>
        <select id="idnum" name="num" class="btn btn-success">
            {% for backupDir in backupDir %}
                <option>{{ backupDir }}</option>
            {% endfor %}
        </select>


        <br \><br \><br \><br \><br \>
        <div id="divd">
            <span>*支持多文件上传，同时上传最多3个文件*</span><br>
            <input type="file" name="file" id="files" class="btn btn-success" aria-hidden="true" multiple="multiple">
        </div>
        <div id="files-info"></div>
        {% if status != '文件上传成功' %}
            <p><font color="red" size="3">{{ status }}</font></p>
        {% endif %}
        <button style="margin-top: 20px" id="tj" type="submit" class="btn btn-primary">提交</button>
        <button style="margin-top: 20px" class="btn btn-warning" type="reset" onclick="reloads()">重置</button>

    </form>
    <hr>

    <div>
        <p class="father btn btn-success">已有数据展示</p>
        <br \>
        <table class="table table-bordered table-hove">
                {% for i in backupData %}
                        <td><font color="green">{{i}}</font></td>
                {% endfor %}
        </table>
    </div>

    <script src="{{ url_for('static', filename='js/file.js') }}"></script>
</body>
</html>